### ISSUE TITLE
Error when inputting api 

### ISSUE THREAD

**Issue by manugratx** [kquinsland/ha-toggl-track#19]
Tried removing the integration and related entities and restarting HA. Also tried installing it manually but to no avail :/ Still get immediately the same error: [%key:common::config_flow::error::unknown%]

Checked the logs and this is what I found:

```
2024-10-27 16:58:23.487 DEBUG (MainThread) [lib_toggl.client] do_get_request
2024-10-27 16:58:23.715 DEBUG (MainThread) [lib_toggl.client] get_account_details
2024-10-27 16:58:23.738 ERROR (MainThread) [custom_components.toggl_track.config_flow] Error creating entry
2024-10-27 16:58:23.738 DEBUG (MainThread) [custom_components.toggl_track.config_flow] Errors in user input. Showing form again. Errors: {'api_key': 'unknown'}
2024-10-27 16:58:23.780 ERROR (MainThread) [frontend.js.modern.202410024] Failed to format translation for key 'component.toggl_track.config.step.user.description' in language 'en'. Error: The intl string context variable "profile_url" was not provided to the string "Please enter your API token from your [Toggl Track Profile page]({profile_url})"
2024-10-27 16:58:39.189 ERROR (MainThread) [frontend.js.modern.202410024] Failed to format translation for key 'component.toggl_track.config.step.user.description' in language 'en'. Error: The intl string context variable "profile_url" was not provided to the string "Please enter your API token from your [Toggl Track Profile page]({profile_url})" 
```
Any help?

**Comment by kquinsland** [comment]
Thanks for opening the issue w/ the debug logs :).

For reference / anybody else that google's their way here in the future:

```yaml
logger:
  default: info
  logs:
    # API client internals
    lib_toggl.client: debug
    # HA specific things
    custom_components.toggl_track: debug
    custom_components.toggl_track.services: debug
```


----

> Any help?


It's been _a while_ since I did any dev work on this; it's gonna be a few min before I can rebuild it / get back into the swing of things but I see two things here:

- Something isn't right about your API key. Make sure you're providing your api key and not password. It will be 32 alphanumeric characters.  Get the API key from here: https://track.toggl.com/profile 

- I've missed _something_ w/ the localization of strings. The HA docs are not super clear about how that all works / precisely what's required to make it work so i'm not that shocked there's bugs here.

**Comment by arunoruto** [comment]
I wanted to try the integration out too, but I got the same error...
I am definitely using the API key from my toggl track profile! My language is set to British English and I got the same error
```log
2024-10-28 21:25:09.210 ERROR (MainThread) [frontend.js.modern.202410024] Failed to format translation for key 'component.toggl_track.config.step.user.description' in language 'en-GB'. Error: The intl string context variable "profile_url" was not provided to the string "Please enter your API token from your [Toggl Track Profile page]({profile_url})"
```
(didn't set the debug message, but the rest should be about the same)

**Comment by kquinsland** [comment]
A +1 is always nice... Even if it's confirming something is broken. 

Currently have my hands full with a few things that are preventing me from rebuilding my Dev environment.  
I might be able to push out some extra verbose logging easily enough.  That wouldn't fix the issue but if you both are in a position to reproduce, the additional verbose login will probably tip me off to where the problem is. 

I'll see if I can carve out an hour this evening to do that...

**Comment by arunoruto** [comment]
Thanks! If I got some time in the upcoming days, I will try to give it a look too!
As for the Dev environment, I can highly suggest using something like direnv, poetry, or if you feel really adventures, try [Nix](https://nixos.org/download/) (+[devenv](https://devenv.sh/)). Really changed the way I write code and it is really reliable :D

**Comment by kquinsland** [comment]
@arunoruto, I use `envrc` and `poetry` :).  I think the NIC on my dev workstation is failing. About 2 of every 3 boots it just ... doesn't enumerate on the PCI-E bus. Quite the inconvenience. Between that and a super obscure docker error preventing the HA dev env from coming up, it's been an "adventure" just trying to get back into the swing of this project.

But I did manage to get a fresh HA dev instance (`24.11.0`, see below) set up and was able to set up the Toggle Track integration just fine :/.




```
Core 2024.11.0.dev0
Frontend 20241002.4
```



Can you and @manugratx give me your HA version and - specifically - what language(s) you're using it with?

Version details come from `http://yourHa/config/info` and language shows up under `http://yourHa/profile/general`


-----


I'll still amp up debug logging around where things appear to be failing for y'all and push out a release... hopefully that'll clue me in.

**Comment by arunoruto** [comment]
That sucks... I have a similar problem on a server and it drives me nuts...

Here is the HA instance version I am running:
```
Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4
```
and the language info:
```Language: English (GB)```

**Comment by kquinsland** [comment]
Ok, @arunoruto , HACS should show this release soon-ish...
https://github.com/kquinsland/ha-toggl-track/releases/tag/v0.1.4

That _should_ solve the `"profile_url" was not provided to the string` error, but i'm super curious about what happens when you hit this code:

```python
            # Hacky info gathering for https://github.com/kquinsland/ha-toggl-track/issues/19
            _LOGGER.error("Exception on entity.create. e: %s", e)
```

**Comment by arunoruto** [comment]
> Ok, @arunoruto , HACS should show this release soon-ish... https://github.com/kquinsland/ha-toggl-track/releases/tag/v0.1.4

Thanks for the quick update!

> That _should_ solve the `"profile_url" was not provided to the string` error, but i'm super curious about what happens when you hit this code:
> 
> ```python
>             # Hacky info gathering for https://github.com/kquinsland/ha-toggl-track/issues/19
>             _LOGGER.error("Exception on entity.create. e: %s", e)
> ```

Now it spits the following error:
```log
2024-10-29 08:34:00.247 ERROR (MainThread) [custom_components.toggl_track.config_flow] Exception on entity.create. e: 1 validation error for Account
country_id
none is not an allowed value (type=type_error.none.not_allowed)
```
The none part is in white then, while the error is in standard red.

**Comment by kquinsland** [comment]
Huh. Ok, that means there's something broken in the underlying library, not the integration.  

After attempting to log in, the api sends something that doesn't match what I was testing against. Almost certainly region specific :/. 

I'll have a look later this week; if I can't reproduce I'll likely ship some additional debug log lines and ask you to share the values here.

**Comment by kquinsland** [comment]
ok @arunoruto and @manugratx I pushed out a [`0.1.5` release](https://github.com/kquinsland/ha-toggl-track/releases/tag/v0.1.5) which uses the latest `lib-toggl` which ... now [treats the `country_id` as optional](https://github.com/kquinsland/lib-toggl/blob/main/lib_toggl/account.py#L40) which should prevent the exception y'all are seeing from being thrown.

If you could, can you provide me a screenshot or tell me what country is listed on your toggle profile page?

![image](https://github.com/user-attachments/assets/cdec7401-8d50-47b6-b582-491ae718555b)

I'm really curious how you both have an account w/o a region. The toggle API docs leave a lot to be desired but they don't really imply that the country is optional /shrug.

**Comment by arunoruto** [comment]
Thanks for the quick help! I didn't notice there was also a country settings for toggl and that this was the culprit, kinda...
I never touched those settings but it displayed the US, improved time, and the default US date format. I just switched the country to Germany and the date format to `dd.mm.yyyy` and now it works, even with version `0.1.3`. Maybe update the README and give a hint, that ppl should fiddle with the locale settings on the profile page!

**Comment by kquinsland** [comment]
> and now it works, even with version 0.1.3.

:confetti_ball: :partying_face: 

> Maybe update the README and give a hint, that ppl should fiddle with the locale settings on the profile page!

As of right now, users w/o the country set should be OK to use this custom component... but I can probably afford to make more of the fields in that object "optional" even if the toggl API docs don't state that some of those can be unset on user profile.

Adding a "if you see X, check Y; discussion $thisGHAIssue" to the readme is simple enough, though. I'll add it to my todo list.

**Comment by manugratx** [comment]
Can also confirm that it works!  The country listed on my profile toggl page was originally the US but I changed it to where I live (Spain) before plugging in my api key and it went through 🎉 Thanks for fix!  🙌🏻

**Comment by kquinsland** [comment]
>  The country listed on my profile toggl page was originally the US 

Hmmm.  I wonder if that's a bug on the Toggl web ui? If there's no country selected in the database/back-end, they just display "USA".
