### ISSUE TITLE
Unique ID is of incorrect type

### ISSUE THREAD

**Issue by kquinsland** [kquinsland/ha-toggl-track#25]
Noticed this in logs today while debugging unrelated issues:

```
ERROR (MainThread) [homeassistant.config_entries] Config entry 'Toggl Track: $myToggleEmail' from integration toggl_track has an invalid unique_id '4123456' of type int when a string is expected, pleas │
│ e create a bug report at https://github.com/kquinsland/ha-toggl-track/issues         
```

Fix should be easy; didn't know that `int` was required...

**Comment by Dunstkreis** [comment]
Was just checking my logs after updating HA, same here. Just gimme a heads up if you need some input for testing or debugging ...

**Comment by kquinsland** [comment]
So this is what HA is complaining about:

https://github.com/kquinsland/ha-toggl-track/blob/771cf5d0d71bc1dc08a68216d6f5b11ff6f7fa6c/custom_components/toggl_track/config_flow.py#L95

It looks like the answer is just `str()`:
https://github.com/home-assistant/core/pull/126911/files

but i'm not sure what the migration(s) required are ...
